name: deployment

on:
  create:
    tags:
      - 'v*'

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest

    steps:
      - name: Install so dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: make build-bundle

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Build)
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/target/release/watchdog
          asset_name: watchdog-x86_64-unknown-linux-gnu
          asset_content_type: application/octet-stream; charset=utf-8